package com.cbmu.bigfoot;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Slf4j
@Controller // This means that this class is a Controller
@CrossOrigin(origins = "*")
@RequestMapping(path="/location") // This means URL's start with /demo (after Application path)
public class LocationController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LocationRepository locationRepository;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Location> getLocations() {
        log.info("Calling getLocations");
        // This returns a JSON or XML with the users
        return locationRepository.findAll();
    }

    @GetMapping(path = "/state/{state}")
    public @ResponseBody
    Iterable<Location> getLocationsByState(@PathVariable("state") String state) {
        log.info("Calling getLocationsByState: {}", state);
        // This returns a JSON or XML with the users
        return locationRepository.findAllByState(state);
    }

    @GetMapping(path = "/county/{county}")
    public @ResponseBody
    Iterable<Location> getLocationsByCounty(@PathVariable("county") String county) {
        log.info("Calling getLocationsByCounty: {}", county);
        // This returns a JSON or XML with the users
        return locationRepository.findAllByCounty(county);
    }

    @GetMapping(path = "/state/{state}/county/{county}")
    public @ResponseBody
    Iterable<Location> getLocationsByStateAndCounty(@PathVariable("state") String state,
                                                    @PathVariable("county") String county) {
        log.info("Calling getLocationsByStateAndCounty: {}/{}", state, county);
        // This returns a JSON or XML with the users
        return locationRepository.findAllByStateAndCounty(state, county);
    }
}
