package com.cbmu.bigfoot;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Slf4j
@Controller // This means that this class is a Controller
@CrossOrigin(origins = "*")
@RequestMapping(path="/weather") // This means URL's start with /demo (after Application path)
public class WeatherController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private WeatherRepository weatherRepository;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Weather> getAllWeather() {
        // This returns a JSON or XML with the users
        return weatherRepository.findAll();
    }
}
