package com.cbmu.covidmap;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;

import java.util.Date;

@Slf4j
@Controller // This means that this class is a Controller
@CrossOrigin(origins = "*") 
@RequestMapping(path="/nyt-counts") // This means URL's start with /demo (after Application path)
public class NytCountsController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NytCountsRepository nytCountsRepository;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<NytCounts> getAllNationalCounts() {
        // This returns a JSON or XML with the users
        return nytCountsRepository.findAll();
    }

    @GetMapping(path = "/state/{state}/date/{date}")
    public @ResponseBody Iterable<NytCounts> getAllByStateAndDate(
            @PathVariable String state,
            @DateTimeFormat(pattern = "yyyy-MM-dd'T'hh:mm:ssZ") @PathVariable Date date) {

        log.info("Searching for all records on {}", date);
        return nytCountsRepository.findAllByStateAndDate(state, date);
    }


}
